{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "media-picker",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.4.aar",
          "url": "media-picker-1.0.4.aar",
          "size": 361547,
          "sha512": "64777ff0beba2cea2616b488cdbedfa3916a1ba725c979aaeaf30cb3c101f114c3293ceaa2196329372eb1d5fbc09afc54678f7ff80adbe483a6e757077958d0",
          "sha256": "e01223f7f3851e5d9c2952df3220ad072642bde887046a4b78b7f75740b457b0",
          "sha1": "36893a1774dbb02a5b39f3ce4c1e9aa6ac6c85f9",
          "md5": "9bc2e43d4c43427859206dc80bf62cf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.candy",
          "module": "preview",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-video",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "top.zibin",
          "module": "luban",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.4.aar",
          "url": "media-picker-1.0.4.aar",
          "size": 361547,
          "sha512": "64777ff0beba2cea2616b488cdbedfa3916a1ba725c979aaeaf30cb3c101f114c3293ceaa2196329372eb1d5fbc09afc54678f7ff80adbe483a6e757077958d0",
          "sha256": "e01223f7f3851e5d9c2952df3220ad072642bde887046a4b78b7f75740b457b0",
          "sha1": "36893a1774dbb02a5b39f3ce4c1e9aa6ac6c85f9",
          "md5": "9bc2e43d4c43427859206dc80bf62cf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-picker-1.0.4-sources.jar",
          "url": "media-picker-1.0.4-sources.jar",
          "size": 47827,
          "sha512": "8c093cbe96ffbcd9c37cdf8fd6fa072cfb886a5b2ccfb7a707543f812ad842e2646738ee75fd38aaea0d5ba87cb4726ebf7e930db83a6583626bc339f413c125",
          "sha256": "befc334346b9f5d009d76e9df26df4d0e457def79f64814e5b4a7eb37ebd38da",
          "sha1": "c29ccaf88f0b3c739f80de99635b5923c212fc70",
          "md5": "c53504e07a9141ef327acc8888dac50f"
        }
      ]
    }
  ]
}
