{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "media-picker",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.4.aar",
          "url": "media-picker-1.0.4.aar",
          "size": 363000,
          "sha512": "1e7c76a71be072175173b6c3ec7e9990b0bb6d8676252fbd4319a49a399b6515f533d8f705aae7ba87a4d2f8ee3dbd3d83955578634dbc87aa8d1eb6238c8e25",
          "sha256": "5ddeba48486a5ab285f1f6d2be84174dbe2221f0ea1a7336b8f168cc3697f680",
          "sha1": "5e1613e61f7f77530423f924892656a33a863751",
          "md5": "ff660a82b4b7ac3277617278a2ca90ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.candy",
          "module": "preview",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-video",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "top.zibin",
          "module": "luban",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.4.aar",
          "url": "media-picker-1.0.4.aar",
          "size": 363000,
          "sha512": "1e7c76a71be072175173b6c3ec7e9990b0bb6d8676252fbd4319a49a399b6515f533d8f705aae7ba87a4d2f8ee3dbd3d83955578634dbc87aa8d1eb6238c8e25",
          "sha256": "5ddeba48486a5ab285f1f6d2be84174dbe2221f0ea1a7336b8f168cc3697f680",
          "sha1": "5e1613e61f7f77530423f924892656a33a863751",
          "md5": "ff660a82b4b7ac3277617278a2ca90ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-picker-1.0.4-sources.jar",
          "url": "media-picker-1.0.4-sources.jar",
          "size": 47862,
          "sha512": "be548424e5e96776d23200b35459ad376d25de20ac8245309fe2a934b8aca50073fcc41f2f5a0c1a2bb788953e34adbef33d545a553bb50efc7119ab53cf0bd5",
          "sha256": "52421702e12c2065bdaa2b0aa88823323923bf5ce2f2ca6598c27acc4b1b4421",
          "sha1": "586936a51973f5443cd2809fb9b09d7f2715c9e4",
          "md5": "aa1f95a90dfc976b5333215336b07a56"
        }
      ]
    }
  ]
}
