{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "media-picker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.0.aar",
          "url": "media-picker-1.0.0.aar",
          "size": 355754,
          "sha512": "c045f6c1e34b6745138dd5d348fde4ebefa726fb051953559b3201bd59c39bf861c0a224da773362080fa3c7192d02007547debdd6a4d687512dbf33068ea334",
          "sha256": "405e08c01f80308baaf7e6687477c506a7c28dc07dd188fafdd63a86e8539f9a",
          "sha1": "57b171aa9203ecc19f0df460d762d9bb44369bcf",
          "md5": "3c48d2fbd9171a56fa2b7bb7099fe584"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.candy",
          "module": "preview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-video",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-picker-1.0.0.aar",
          "url": "media-picker-1.0.0.aar",
          "size": 355754,
          "sha512": "c045f6c1e34b6745138dd5d348fde4ebefa726fb051953559b3201bd59c39bf861c0a224da773362080fa3c7192d02007547debdd6a4d687512dbf33068ea334",
          "sha256": "405e08c01f80308baaf7e6687477c506a7c28dc07dd188fafdd63a86e8539f9a",
          "sha1": "57b171aa9203ecc19f0df460d762d9bb44369bcf",
          "md5": "3c48d2fbd9171a56fa2b7bb7099fe584"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-picker-1.0.0-sources.jar",
          "url": "media-picker-1.0.0-sources.jar",
          "size": 47672,
          "sha512": "657ddfc928bac6e343b9e43afd707701c4a3436074e203d3128a3cd16487155bd5a814e7fd29e4b407479b0a75c1aa63a9352e04d8cdbb58475d94b949100f61",
          "sha256": "5e9ef52d04c7ddebeb46e8c1503c1e6c7aad1669ec9fddccc62d459d62fef8da",
          "sha1": "b47a852075a7c908c9f26bc920170f5d41aa4a0d",
          "md5": "c30dca960eb083bf07598b88962ac831"
        }
      ]
    }
  ]
}
