{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "kit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.0.aar",
          "url": "kit-1.0.0.aar",
          "size": 190465,
          "sha512": "02b388ce570ccef7f5a68bb6fba5be47d22cd44233e42b64763c1faa94ebacfb8f04a901cb38b3f007500607d91863e1db1720af63130f01a3e5fa415c83f2d4",
          "sha256": "82a94da8f5ed7b569d6e8615efac0b40cad226710ffce9d4adff8ee1b33e9498",
          "sha1": "2eaa69d3ac27b1f256dcfa9f47d4948ff8e49357",
          "md5": "a708f3c7e868b4232e1363cf07cbc0e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.0.aar",
          "url": "kit-1.0.0.aar",
          "size": 190465,
          "sha512": "02b388ce570ccef7f5a68bb6fba5be47d22cd44233e42b64763c1faa94ebacfb8f04a901cb38b3f007500607d91863e1db1720af63130f01a3e5fa415c83f2d4",
          "sha256": "82a94da8f5ed7b569d6e8615efac0b40cad226710ffce9d4adff8ee1b33e9498",
          "sha1": "2eaa69d3ac27b1f256dcfa9f47d4948ff8e49357",
          "md5": "a708f3c7e868b4232e1363cf07cbc0e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kit-1.0.0-sources.jar",
          "url": "kit-1.0.0-sources.jar",
          "size": 40839,
          "sha512": "b17a20b6c343f142ebd923bb5ced0b9fba84b04cb261d54f41ce72e3ace4a093c4e134cb89860b70a67fdcd6072075e831309927012db24075b4427f8d59d11b",
          "sha256": "7ff50a2b2033d37423c30f0d8f6f25b3364fff34c931228899e51a0936e17df2",
          "sha1": "4605d7fc089319da65b6576a61d840c193adee40",
          "md5": "4d43a4225a3b92955d0b8b183c58e5df"
        }
      ]
    }
  ]
}
