{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "preview",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.candy",
          "module": "zoomable",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "preview-1.0.0.aar",
          "url": "preview-1.0.0.aar",
          "size": 162366,
          "sha512": "1970542057862b53f0ee065e1fa1b8a89c5e252ad8b8d8fdc231f63cb8baae3f8341d5141304d00c25579f2c93a5c67d68b9896ea872f39954ffb17dc611bd3d",
          "sha256": "5f338b200840fa851fa8d78c5e4c1d31710f58a6acedb4111242489d40cbe92e",
          "sha1": "05727146f897ac126a839081f1e9970eb6ec8f76",
          "md5": "c9c01012a9e6b0c42ae066280a643f26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-video",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.candy",
          "module": "zoomable",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "preview-1.0.0.aar",
          "url": "preview-1.0.0.aar",
          "size": 162366,
          "sha512": "1970542057862b53f0ee065e1fa1b8a89c5e252ad8b8d8fdc231f63cb8baae3f8341d5141304d00c25579f2c93a5c67d68b9896ea872f39954ffb17dc611bd3d",
          "sha256": "5f338b200840fa851fa8d78c5e4c1d31710f58a6acedb4111242489d40cbe92e",
          "sha1": "05727146f897ac126a839081f1e9970eb6ec8f76",
          "md5": "c9c01012a9e6b0c42ae066280a643f26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preview-1.0.0-sources.jar",
          "url": "preview-1.0.0-sources.jar",
          "size": 22326,
          "sha512": "443a2ebf5ca2d9e4051731095209f4fc8dc57bc5415306097b6f283559ec89f32128cac9776e7e02579afa2bdc4382c7b6838f8cb3b5d4ea8c2e61780e162fd6",
          "sha256": "e1adb73c6badda9d04fcd75d9ddf68419b7c6f92b5192acf03c1acd4a44bcf42",
          "sha1": "a5295ec446346ea6414572c092a7c73debded586",
          "md5": "0c76d11da89622202d001e834a8c0436"
        }
      ]
    }
  ]
}
