{
  "formatVersion": "1.1",
  "component": {
    "group": "com.candy",
    "module": "ui",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 299757,
          "sha512": "871666eb22633c0044c2cfd92eb587a5ee4c4614b13ae7440ef2712d60d897a59e38276cae3d376ee125ee628bbaca70d4441ca0997b334fbafe8c4fa30686e9",
          "sha256": "83e25bb6ac48162fd7edfec0dab36aac3e01642bebe9347188f59d826b76e45c",
          "sha1": "c6f5af6cdf183864ac80da46d36edb561c030408",
          "md5": "689c201a40b20fe1443baf2064b54f96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.candy",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 299757,
          "sha512": "871666eb22633c0044c2cfd92eb587a5ee4c4614b13ae7440ef2712d60d897a59e38276cae3d376ee125ee628bbaca70d4441ca0997b334fbafe8c4fa30686e9",
          "sha256": "83e25bb6ac48162fd7edfec0dab36aac3e01642bebe9347188f59d826b76e45c",
          "sha1": "c6f5af6cdf183864ac80da46d36edb561c030408",
          "md5": "689c201a40b20fe1443baf2064b54f96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.0.0-sources.jar",
          "url": "ui-1.0.0-sources.jar",
          "size": 60714,
          "sha512": "b7d89398927033410563ab9819aa076e1391b1c3c881d670e672a37fae82ed52a8f98088c9229ee3bb18d7ea7656c2f92cd381470ea7b057e1fd99bfa8818351",
          "sha256": "ee22af460c1a68e999757e035386a1bfba2e6648b4c5911077f437e4fa5174b6",
          "sha1": "83807516d18413d6c64a1b156ca68e9d4f747a2f",
          "md5": "7f82a75dbd91b9959fffaf0fc7d2e348"
        }
      ]
    }
  ]
}
